git config --global alias.pushh !$(realpath ./git-pushh.sh)
git config --global alias.committ !$(realpath ./git-committ.sh)
git config --global alias.logg !$(realpath ./git-logg.sh)
git config --global alias.mergee !$(realpath ./git-mergee.sh)
git config --global alias.cleanupp !$(realpath ./git-cleanupp.sh)
git config --global alias.amendee !$(realpath ./git-amendee.sh)